# Script 5 — data quality report (just print, no file)
import pandas as pd
ts = pd.read_csv('timeseries.csv')
sm = pd.read_csv('sensor_metadata.csv')
print('Total timeseries rows:', len(ts))
print('Unique sensors in timeseries:', ts['sensor_id'].nunique())
print('Date range:', ts['timestamp'].min(), 'to', ts['timestamp'].max())
print('Quality flags:\n', ts['quality_flag'].value_counts().to_string())
missing = set(sm['sensor_id']) - set(ts['sensor_id'])
extra = set(ts['sensor_id']) - set(sm['sensor_id'])
print('In metadata but missing from timeseries:', missing if missing else 'NONE')
print('In timeseries but not in metadata:', extra if extra else 'NONE')